# Generated by Django 3.2.23 on 2023-11-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('datatime', models.DateField(auto_now_add=True)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
