# Generated by Django 3.2.23 on 2023-11-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Project_Blog',
        ),
    ]
