# Generated by Django 3.2.23 on 2023-11-22 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_project_project_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_blog',
            name='datatime',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project_blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
